### ISSUE TITLE
Docs website, padding.

### ISSUE THREAD

**Issue by justingeeslin** [CogTool-Modern/cogtool#48]
I think some padding around the main content to match the navigation would be helpful.

<img width="1415" alt="Screen Shot 2020-07-30 at 6 16 36 AM" src="https://user-images.githubusercontent.com/1075425/88916860-6bf78900-d22c-11ea-8d24-ad1c4e143982.png">

The navigation's padding is this (style.css:282):
```css
@media only screen and (min-width: 768px)
.site-branding {
   margin: 0 calc(10% + 60px);
}
```

This margin applied to `.site-content` looks great. 

<img width="1680" alt="Screen Shot 2020-07-30 at 6 21 36 AM" src="https://user-images.githubusercontent.com/1075425/88917173-f04a0c00-d22c-11ea-82b5-ac64e35d0dfd.png">
